name: Release Go Client

on:
  push:
    tags:
      - "v*" # runs only when you push a tag like v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.6"

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/bizhawk-client-windows-amd64.exe ./...
          GOOS=linux   GOARCH=amd64 go build -o dist/bizhawk-client-linux-amd64 ./...
          GOOS=darwin  GOARCH=amd64 go build -o dist/bizhawk-client-macos-amd64 ./...

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/bizhawk-client-windows-amd64.exe
            dist/bizhawk-client-linux-amd64
            dist/bizhawk-client-macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}