name: Build Go Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.6'

      - name: Build .exe
        run: |
          go mod tidy
          go build -o dist/bizhawk-client.exe ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bizhawk-client-windows
          path: dist/bizhawk-client.exe

  # Optional: cross-compile for Linux/Mac too
  build-cross:
    name: Cross-compile (Linux & macOS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=windows GOARCH=amd64 go build -o dist/bizhawk-client.exe ./...
          GOOS=linux GOARCH=amd64 go build -o dist/bizhawk-client ./...
          GOOS=darwin GOARCH=amd64 go build -o dist/bizhawk-client-macos ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bizhawk-client-cross
          path: dist/*